services:
  logger_library:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - log_server
    networks:
      - log_network

  log_server:
    build:
      context: ./log_server
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      - log_network

networks:
  log_network:
    driver: bridge