version: '3.8'

services:
  logger_library:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - log_server
    volumes:
      - ./logger_library:/logger_library
    networks:
      - log_network

  log_server:
    build:
      context: ./log_server
    ports:
      - "8080:8080"
    networks:
      - log_network

networks:
  log_network:
    driver: bridge