name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs_on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y libboost-all-dev

      - name: Build and run tests
        run: |
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp *.a /usr/lib

      - name: Configure CMake
        run: cmake .

      - name: Build
        run: cmake --build .

      - name: Run tests
        run: ctest --output-on-failure