@startuml
class Logger {
  - level: LogLevel
  - formatter: LogFormatter
  - destinationManager: LogDestinationManager
  + log(level: LogLevel, message: string): void
}

class LogFormatter {
  + format(level: LogLevel, moduleName: string, message: string): string
}

interface LogDestination {
  + log(log: string): void
}

class LogDestinationManager {
  - destinations: List<LogDestination>
  + logToFile(log: string): void
  + logToNetwork(log: string): void
  + addDestination(destination: LogDestination): void
  + logToAllDestinations(log: string): void
}

class FileLogger {
  - fileName: string
  - maxSize: int
  + log(log: string): void
  + rotateFiles(): void
}

class NetworkLogger {
  - endpoint: string
  - apiClient: RESTAPIClient
  + log(log: string): void
}

class RESTAPIClient {
  - endpoint: string
  + post(log: string): void
}

Logger --> LogFormatter
Logger --> LogDestinationManager
LogDestinationManager --> LogDestination
LogDestination <|-- FileLogger
LogDestination <|-- NetworkLogger
NetworkLogger --> RESTAPIClient
@enduml
